# Generated by Django 6.0.6 on 2026-06-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_bookissue_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookissue',
            name='transaction_type',
            field=models.CharField(default='Issued', max_length=50),
        ),
    ]
